apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: gym-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom: { secretKeyRef: { name: bot-secrets, key: POSTGRES_DB } }
          - name: POSTGRES_USER
            valueFrom: { secretKeyRef: { name: bot-secrets, key: POSTGRES_USER } }
          - name: POSTGRES_PASSWORD
            valueFrom: { secretKeyRef: { name: bot-secrets, key: POSTGRES_PASSWORD } }
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gym-prod
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
