"""Add cascade delete for Admin/User Exercise

Revision ID: 45059d30a27e
Revises: 03f278607aa3
Create Date: 2024-12-20 18:46:54.350665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45059d30a27e'
down_revision: Union[str, None] = '03f278607aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
