"""Add circle training support

Revision ID: f79c16648e14
Revises: 45059d30a27e
Create Date: 2024-12-21 04:25:21.709106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79c16648e14'
down_revision: Union[str, None] = '45059d30a27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('circle_training', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'circle_training')
    # ### end Alembic commands ###
