"""Fix user_exercise

Revision ID: 03f278607aa3
Revises: 78b1121a51ad
Create Date: 2024-12-10 19:14:34.582055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f278607aa3'
down_revision: Union[str, None] = '78b1121a51ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_exercises_name_key', 'user_exercises', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_exercises_name_key', 'user_exercises', ['name'])
    # ### end Alembic commands ###
